# ===== Gesture Thresholds =====
PINCH_THRESHOLD = 0.035

SWIPE_THRESHOLD = 60
SWIPE_COOLDOWN = 0.5

DWELL_TIME = 3.0
DWELL_MOVEMENT_THRESHOLD = 20

# ===== System Timing =====
FIST_HOLD_TIME = 3.0
ACTIVATION_HOLD_TIME = 3.0
NO_HAND_TIMEOUT = 3.0

ACTION_COOLDOWN = 1.0

# ===== Camera =====
CAMERA_PC = 0
CAMERA_PHONE = 1
DEFAULT_CAMERA = CAMERA_PC

FRAME_WIDTH = 640
FRAME_HEIGHT = 480
FRAME_SKIP = 3   # cap.grab()

# ===== Cursor Mapping (สำคัญมาก) =====
CAMERA_MIN_X = 0.20
CAMERA_MAX_X = 0.80
CAMERA_MIN_Y = 0.15
CAMERA_MAX_Y = 0.85

# ===== Smoothing =====
SMOOTHING_SLOW = 0.2
SMOOTHING_MEDIUM = 0.35
SMOOTHING_FAST = 0.5

# ===== Preview UI =====
PREVIEW_WIDTH = 480
PREVIEW_HEIGHT = 360